/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EKOCHAVA_AUTODEFS_H
#define S3EKOCHAVA_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_KOCHAVA_NAME "s3eKochava"
#define S3E_EXT_KOCHAVA_HASH 0xa7eec10d

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("s3eKochava", 6)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !S3EKOCHAVA_AUTODEFS_H */
