/*
 * (C) 2001-2012 Marmalade. All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Marmalade.
 *
 * This file consists of source code released by Marmalade under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_KOCHAVA_H
#define S3E_EXT_KOCHAVA_H

// s3eKochava
// Enable Kochava in Marmalade

/**
 * This extension allows the application to utilize the Kochava API
 */
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the Kochava extension is available.
 */
s3eBool s3eKochavaAvailable();

/**
 * Call this in your application initialization
 *
 * @param appId		The Kochava App Id of the game for the current platform
 */
void s3eKochavaCreate(const char* appId);

/**
 * API to track any post-install events
 *
 * @param eventName		The name of the event
 * @param eventData		The value of the event as a String
 */
void s3eKochavaEvent(const char* eventName, const char* eventData);

/**
 * API to track any post-install spatial events (i.e. with 3d coordinates)
 *
 * @param eventName		The name of the event
 * @param x				The x coordinate
 * @param y				The y coordinate
 * @param z				The z coordinate
 * @param eventData		The value of the event as a String
 */
void s3eKochavaEventSpatial(const char* eventName, int x, int y, int z, const char* eventData);

/**
 * Pass deep link events to Kochava using this method.
 *
 * @param uri		The URI of the deep link
 */
void s3eKochavaDeepLinkEvent(const char* uri);

/**
 * If you are having problems with your integration, you can enable debug logging to possibly gain some insight as to what the problem might be.
 *
 * @param value		The value to set EnableDebug to (by default it is false)
 */
void s3eKochavaEnableDebug(bool value);

/**
 * By default, the Kochava SDK provides error messages to assist in debugging problems you might be having with integrating the SDK into your app.
 * If you would like to turn these off, you can use this method
 *
 * @param value		The value to set SetErrorDebug to (by default it is true)
 */
void s3eKochavaSetErrorDebug(bool value);

S3E_END_C_DECL

#endif /* !S3E_EXT_KOCHAVA_H */
